# Generated by Django 3.2.11 on 2022-01-23 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220123_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
