# Generated by Django 3.2.11 on 2022-01-24 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_resource_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
