# Generated by Django 3.2.11 on 2022-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_resource_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='institution_is_oeg_member',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='twitter_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='twitter_personal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
