# Generated by Django 3.2.16 on 2022-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20220126_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="year",
            field=models.IntegerField(blank=True, default=2023, null=True),
        ),
    ]
