# Generated by Django 3.2.16 on 2023-01-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_auto_20230108_2017"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailQueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=128)),
                ("from_email", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("priority", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("s", "sent"), ("u", "not sent yet")],
                        default="u",
                        max_length=1,
                    ),
                ),
                ("context", models.CharField(max_length=512)),
                ("recipient_list", models.CharField(max_length=512)),
            ],
        ),
    ]
