# Generated by Django 3.2.16 on 2023-01-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_alter_emailqueueitem_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailqueueitem",
            name="cc",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
