# Generated by Django 3.2.16 on 2023-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_emailqueueitem_cc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("r_a", "resource: approved"),
                            ("r_f", "resource: feedback sent"),
                            ("r_r", "resource: rejected"),
                        ],
                        max_length=3,
                    ),
                ),
                ("subject", models.CharField(max_length=128)),
                ("body", models.TextField(blank=True)),
            ],
        ),
    ]
