# Generated by Django 3.2.16 on 2023-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_emailnotificationtext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailqueueitem",
            name="context",
        ),
        migrations.RemoveField(
            model_name="emailqueueitem",
            name="template_name",
        ),
        migrations.AddField(
            model_name="emailqueueitem",
            name="body",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailqueueitem",
            name="subject",
            field=models.CharField(default="unknown", max_length=128),
            preserve_default=False,
        ),
    ]
