# Generated by Django 3.2.16 on 2023-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_alter_emailnotificationtext_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotificationtext",
            name="action",
            field=models.CharField(
                choices=[
                    ("a_n", "account: new"),
                    ("r_n", "resource: new"),
                    ("r_a", "resource: approved"),
                    ("r_f", "resource: feedback sent"),
                    ("r_r", "resource: rejected"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
