# Generated by Django 3.2.16 on 2023-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_alter_emailnotificationtext_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
