# Generated by Django 3.2.17 on 2023-02-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_auto_20230126_1540"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="opentags_old",
            new_name="opentags_csv",
        ),
    ]
