# Generated by Django 3.2.16 on 2022-10-24 15:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='anniversary_image',
            field=models.ForeignKey(blank=True, help_text='Anniversary image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='"Call to action" body', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_faq',
            field=models.CharField(default='FAQ', help_text='Text to display on FAQ link', max_length=255, verbose_name='FAQ link text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_faq_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the FAQ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='FAQ page link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_image',
            field=models.ForeignKey(blank=True, help_text='Main image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main body', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Main image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main intro', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='md_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='"More details" body', null=True),
        ),
    ]
