# Generated by Django 3.2.16 on 2022-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20221024_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(
                max_length=254, null=True, verbose_name='"Call to action" title'
            ),
        ),
    ]
