# Generated by Django 3.2.16 on 2022-11-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0005_homepage_cta_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="cta_image",
            field=models.ForeignKey(
                blank=True,
                help_text='"Call to action" image',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
